name: Build Padavan

on:
  push:
    branches: [ test1 ]
  pull_request:
    branches: [ test1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
        else
        git clone --depth=1 https://github.com/sknnks/rt-n56uB.git /opt/rt-n56u
        fi
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware1
      env:
        TNAME: PSG1218
        KERNEL: 3.4
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ######################################################
        sed -i '/CONFIG_MTD_STORE_PART_SIZ/c\CONFIG_MTD_STORE_PART_SIZ=0x900000' configs/boards/PSG1218/kernel-3.4.x.config
        sed -i '/size_tmp="24M"/c\size_tmp="8M"' user/scripts/dev_init.sh
        sed -i '/size_etc="6M"/c\size_etc="2M"' user/scripts/dev_init.sh
        sed -i '/size_var="4M"/c\size_var="2M"' user/scripts/dev_init.sh
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
